//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTgBot.Infrastructure.Conversations.Administration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdministrationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministrationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminTgBot.Infrastructure.Conversations.Administration.AdministrationText", typeof(AdministrationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить группу прав.
        /// </summary>
        internal static string AddRightGroup {
            get {
                return ResourceManager.GetString("AddRightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1})
        ///
        ///Группы прав: {2}
        ///Отдельные права: {3}.
        /// </summary>
        internal static string AdminDetails {
            get {
                return ResourceManager.GetString("AdminDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа прав &quot;{0}&quot;
        ///
        ///Включает права: {1}.
        /// </summary>
        internal static string AdminGroupDetails {
            get {
                return ResourceManager.GetString("AdminGroupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление группами сотрудника.
        /// </summary>
        internal static string AdminGroupManaging {
            get {
                return ResourceManager.GetString("AdminGroupManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник не найден.
        /// </summary>
        internal static string AdminNotFound {
            get {
                return ResourceManager.GetString("AdminNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string AdminPreview {
            get {
                return ResourceManager.GetString("AdminPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление отдельными правами пользователя.
        /// </summary>
        internal static string AdminRightsManaging {
            get {
                return ResourceManager.GetString("AdminRightsManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить группу прав?.
        /// </summary>
        internal static string ApproveAddingRightGroup {
            get {
                return ResourceManager.GetString("ApproveAddingRightGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться в предыдущий раздел.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к списку групп.
        /// </summary>
        internal static string BackFromAddRightGroupName {
            get {
                return ResourceManager.GetString("BackFromAddRightGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к вводу имени группы.
        /// </summary>
        internal static string BackToEnterRightGroupName {
            get {
                return ResourceManager.GetString("BackToEnterRightGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены? Все пользователи будут исключены из этой группы после удаления.
        /// </summary>
        internal static string DeleteGroupApprove {
            get {
                return ResourceManager.GetString("DeleteGroupApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пусто.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В этой группе пока нет прав.
        /// </summary>
        internal static string EmptyGroup {
            get {
                return ResourceManager.GetString("EmptyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описание группы.
        /// </summary>
        internal static string EnterRightGroupDescription {
            get {
                return ResourceManager.GetString("EnterRightGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя группы прав.
        /// </summary>
        internal static string EnterRightGroupName {
            get {
                return ResourceManager.GetString("EnterRightGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа &quot;{0}&quot; удалена успешно.
        /// </summary>
        internal static string GroupDeleted {
            get {
                return ResourceManager.GetString("GroupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление группами прав.
        /// </summary>
        internal static string GroupManaging {
            get {
                return ResourceManager.GetString("GroupManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление группой прав
        ///
        ///Наименование: {0}
        ///Описание: {1}.
        /// </summary>
        internal static string GroupRights {
            get {
                return ResourceManager.GetString("GroupRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление правами группы.
        /// </summary>
        internal static string GroupRightsManaging {
            get {
                return ResourceManager.GetString("GroupRightsManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌Исключить.
        /// </summary>
        internal static string GroupTurnOff {
            get {
                return ResourceManager.GetString("GroupTurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Включить.
        /// </summary>
        internal static string GroupTurnOn {
            get {
                return ResourceManager.GetString("GroupTurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление правами группы.
        /// </summary>
        internal static string ManageGroupRights {
            get {
                return ResourceManager.GetString("ManageGroupRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные утеряны. Попробуйте заново добавить группу.
        /// </summary>
        internal static string NewRightGroupLost {
            get {
                return ResourceManager.GetString("NewRightGroupLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы прав.
        /// </summary>
        internal static string PermissionGroups {
            get {
                return ResourceManager.GetString("PermissionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдельные права.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование: {0}
        ///Описание: {1}.
        /// </summary>
        internal static string RightDetails {
            get {
                return ResourceManager.GetString("RightDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа &quot;{0}&quot; успешно добавлена.
        /// </summary>
        internal static string RightGroupAdded {
            get {
                return ResourceManager.GetString("RightGroupAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа прав не найдена.
        /// </summary>
        internal static string RightGroupLost {
            get {
                return ResourceManager.GetString("RightGroupLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа прав с id &quot;{0}&quot; не найдена.
        /// </summary>
        internal static string RightGroupNotFound {
            get {
                return ResourceManager.GetString("RightGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группы прав.
        /// </summary>
        internal static string RightGroups {
            get {
                return ResourceManager.GetString("RightGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Права с id &quot;{0}&quot; не найдены.
        /// </summary>
        internal static string RightNotFound {
            get {
                return ResourceManager.GetString("RightNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Права.
        /// </summary>
        internal static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление правами и группами прав.
        /// </summary>
        internal static string RightsMenu {
            get {
                return ResourceManager.GetString("RightsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌Убрать.
        /// </summary>
        internal static string RightTurnOff {
            get {
                return ResourceManager.GetString("RightTurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Добавить.
        /// </summary>
        internal static string RightTurnOn {
            get {
                return ResourceManager.GetString("RightTurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите сотрудника.
        /// </summary>
        internal static string ShowAdminList {
            get {
                return ResourceManager.GetString("ShowAdminList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр всех прав пользователей.
        /// </summary>
        internal static string ShowRights {
            get {
                return ResourceManager.GetString("ShowRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдельные права.
        /// </summary>
        internal static string UserRights {
            get {
                return ResourceManager.GetString("UserRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в раздел администрирования.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
