//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTgBot.Infrastructure.Conversations.Lkk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LkkConversationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LkkConversationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminTgBot.Infrastructure.Conversations.Lkk.LkkConversationText", typeof(LkkConversationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите новый пароль.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать. Попробуйте ввести снова.
        /// </summary>
        internal static string ConfirmNewPasswordNotSame {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить имя.
        /// </summary>
        internal static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя успешно изменено.
        /// </summary>
        internal static string EditNameSuccess {
            get {
                return ResourceManager.GetString("EditNameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        internal static string EditPassword {
            get {
                return ResourceManager.GetString("EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыл пароль.
        /// </summary>
        internal static string EditPasswordForgot {
            get {
                return ResourceManager.GetString("EditPasswordForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успешно изменен.
        /// </summary>
        internal static string EditPasswordSuccess {
            get {
                return ResourceManager.GetString("EditPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новый пароль.
        /// </summary>
        internal static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Похоже, ваш новый пароль потерялся. Попробуйте повторить операцию в личном кабинете.
        /// </summary>
        internal static string NewPasswordLost {
            get {
                return ResourceManager.GetString("NewPasswordLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя должно отличаться. Попробуйте ввести снова.
        /// </summary>
        internal static string SameNameError {
            get {
                return ResourceManager.GetString("SameNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль должен отличаться от текущего. Попробуйте ввести снова.
        /// </summary>
        internal static string SamePasswordError {
            get {
                return ResourceManager.GetString("SamePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее значение: {0}
        ///Введите новое.
        /// </summary>
        internal static string SuggestEditName {
            get {
                return ResourceManager.GetString("SuggestEditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите старый пароль.
        /// </summary>
        internal static string SuggestEditPassword {
            get {
                return ResourceManager.GetString("SuggestEditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в личный кабинет, {0}.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пароль. Попробуйте снова.
        /// </summary>
        internal static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
    }
}
