//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTgBot.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminTgBot.Infrastructure.MessagesText", typeof(MessagesText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не авторизованы.
        /// </summary>
        internal static string AuthFail {
            get {
                return ResourceManager.GetString("AuthFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        internal static string CommandAdministration {
            get {
                return ResourceManager.GetString("CommandAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /buttons.
        /// </summary>
        internal static string CommandButtons {
            get {
                return ResourceManager.GetString("CommandButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать кнопки меню.
        /// </summary>
        internal static string CommandButtonsDescriptions {
            get {
                return ResourceManager.GetString("CommandButtonsDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор товаров.
        /// </summary>
        internal static string CommandCatalogEditor {
            get {
                return ResourceManager.GetString("CommandCatalogEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный кабинет.
        /// </summary>
        internal static string CommandLkk {
            get {
                return ResourceManager.GetString("CommandLkk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        internal static string CommandOrders {
            get {
                return ResourceManager.GetString("CommandOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /start.
        /// </summary>
        internal static string CommandStart {
            get {
                return ResourceManager.GetString("CommandStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернитесь к последнему сообщению.
        /// </summary>
        internal static string GoLastMessage {
            get {
                return ResourceManager.GetString("GoLastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите текст.
        /// </summary>
        internal static string MessageTextExcepted {
            get {
                return ResourceManager.GetString("MessageTextExcepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string NoPagination {
            get {
                return ResourceManager.GetString("NoPagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас недостаточно прав для совершения данного действия.
        /// </summary>
        internal static string NotEnoughRights {
            get {
                return ResourceManager.GetString("NotEnoughRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt;.
        /// </summary>
        internal static string PaginationNext {
            get {
                return ResourceManager.GetString("PaginationNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string PaginationPrevious {
            get {
                return ResourceManager.GetString("PaginationPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так.
        /// </summary>
        internal static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная команда.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение слишком длинное. Разрешенная длина: {0}.
        /// </summary>
        internal static string ValueTooLong {
            get {
                return ResourceManager.GetString("ValueTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение слишком короткое. Минимальная длина: {0}.
        /// </summary>
        internal static string ValueTooShort {
            get {
                return ResourceManager.GetString("ValueTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
