//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTgBot.Infrastructure.Conversations.CatalogEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatalogEditorText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogEditorText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminTgBot.Infrastructure.Conversations.CatalogEditor.CatalogEditorText", typeof(CatalogEditorText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить категорию.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый товар.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить точку продаж.
        /// </summary>
        internal static string AddSellLocation {
            get {
                return ResourceManager.GetString("AddSellLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить?.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Значение отсутствует *.
        /// </summary>
        internal static string AttributeNoValue {
            get {
                return ResourceManager.GetString("AttributeNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться в предыдущий раздел.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к категориям.
        /// </summary>
        internal static string BackToCategories {
            get {
                return ResourceManager.GetString("BackToCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к категории.
        /// </summary>
        internal static string BackToCategory {
            get {
                return ResourceManager.GetString("BackToCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория: {0}.
        /// </summary>
        internal static string CategoryActions {
            get {
                return ResourceManager.GetString("CategoryActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая категория
        ///
        ///Наименование: {0}.
        /// </summary>
        internal static string CategoryPreview {
            get {
                return ResourceManager.GetString("CategoryPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимость категории.
        /// </summary>
        internal static string CategoryVisibility {
            get {
                return ResourceManager.GetString("CategoryVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить наименование.
        /// </summary>
        internal static string ChangeSellLocation {
            get {
                return ResourceManager.GetString("ChangeSellLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите категорию.
        /// </summary>
        internal static string ChoosingCategory {
            get {
                return ResourceManager.GetString("ChoosingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string DeleteSellLocation {
            get {
                return ResourceManager.GetString("DeleteSellLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите удалить точку продаж?.
        /// </summary>
        internal static string DeleteSellLocationConfirm {
            get {
                return ResourceManager.GetString("DeleteSellLocationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить товар.
        /// </summary>
        internal static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Атрибут:&lt;/b&gt; {0}
        ///
        ///&lt;b&gt;Текущее значение:&lt;/b&gt;  {1}.
        /// </summary>
        internal static string EditProductAttributeTemplate {
            get {
                return ResourceManager.GetString("EditProductAttributeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пусто.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите {0}.
        /// </summary>
        internal static string EnterProductAttribute {
            get {
                return ResourceManager.GetString("EnterProductAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите значение.
        /// </summary>
        internal static string EnterValue {
            get {
                return ResourceManager.GetString("EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Смотри фото *.
        /// </summary>
        internal static string LookPhoto {
            get {
                return ResourceManager.GetString("LookPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары и категории.
        /// </summary>
        internal static string ManageCatalog {
            get {
                return ResourceManager.GetString("ManageCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точки продаж.
        /// </summary>
        internal static string ManageSellLocations {
            get {
                return ResourceManager.GetString("ManageSellLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не забудьте изменить видимость категории. По умолчанию она отключена.
        /// </summary>
        internal static string NewCategoryRemind {
            get {
                return ResourceManager.GetString("NewCategoryRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при загрузке фотографии. Попробуйте другую ссылку.
        /// </summary>
        internal static string PhotoLoadFail {
            get {
                return ResourceManager.GetString("PhotoLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание товара.
        /// </summary>
        internal static string ProductDesciption {
            get {
                return ResourceManager.GetString("ProductDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt;
        ///
        ///&lt;i&gt;{1}&lt;/i&gt;
        ///
        ///{2}.
        /// </summary>
        internal static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наименование товара.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотография товара (ссылка).
        /// </summary>
        internal static string ProductPhoto {
            get {
                return ResourceManager.GetString("ProductPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена товара.
        /// </summary>
        internal static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары отсутствуют.
        /// </summary>
        internal static string ProductsNotFound {
            get {
                return ResourceManager.GetString("ProductsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимость товара.
        /// </summary>
        internal static string ProductVisibility {
            get {
                return ResourceManager.GetString("ProductVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к выбору атрибута.
        /// </summary>
        internal static string ReturnToAttributeEditor {
            get {
                return ResourceManager.GetString("ReturnToAttributeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к товару.
        /// </summary>
        internal static string ReturnToProduct {
            get {
                return ResourceManager.GetString("ReturnToProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая точка продаж успешно добавлена.
        /// </summary>
        internal static string SellLocationAdded {
            get {
                return ResourceManager.GetString("SellLocationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка продаж успешно изменена.
        /// </summary>
        internal static string SellLocationChangeSuccess {
            get {
                return ResourceManager.GetString("SellLocationChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка продаж успешно удалена.
        /// </summary>
        internal static string SellLocationDeleteSuccess {
            get {
                return ResourceManager.GetString("SellLocationDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка продаж &quot;{0}&quot;.
        /// </summary>
        internal static string SellLocationDetails {
            get {
                return ResourceManager.GetString("SellLocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление точками продаж.
        /// </summary>
        internal static string SellLocations {
            get {
                return ResourceManager.GetString("SellLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую точку продаж?.
        /// </summary>
        internal static string SellLocationSuggestConfirm {
            get {
                return ResourceManager.GetString("SellLocationSuggestConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите наименование новой торговой точки.
        /// </summary>
        internal static string SellLocationSuggestEnterName {
            get {
                return ResourceManager.GetString("SellLocationSuggestEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать товары.
        /// </summary>
        internal static string ShowProducts {
            get {
                return ResourceManager.GetString("ShowProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите наименование.
        /// </summary>
        internal static string SuggestChangeSellLocationName {
            get {
                return ResourceManager.GetString("SuggestChangeSellLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ввести текст.
        /// </summary>
        internal static string TextRequired {
            get {
                return ResourceManager.GetString("TextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст слишком длинный. Введите короче.
        /// </summary>
        internal static string TextTooLong {
            get {
                return ResourceManager.GetString("TextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть.
        /// </summary>
        internal static string VisibilityOff {
            get {
                return ResourceManager.GetString("VisibilityOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        internal static string VisibilityOn {
            get {
                return ResourceManager.GetString("VisibilityOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в раздел управления товарам и категориями. А также точками продаж.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите корректное значение.
        /// </summary>
        internal static string WrongValue {
            get {
                return ResourceManager.GetString("WrongValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
