//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuTgBot.Infrastructure.Conversations.Orders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrdersText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrdersText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuTgBot.Infrastructure.Conversations.Orders.OrdersText", typeof(OrdersText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀️ Назад.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возврат....
        /// </summary>
        internal static string BackFromPhone {
            get {
                return ResourceManager.GetString("BackFromPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить адрес.
        /// </summary>
        internal static string ChangeAddress {
            get {
                return ResourceManager.GetString("ChangeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить номер телефона.
        /// </summary>
        internal static string ChangePhone {
            get {
                return ResourceManager.GetString("ChangePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите адрес доставки
        ///
        ///{0}.
        /// </summary>
        internal static string ChooseAddress {
            get {
                return ResourceManager.GetString("ChooseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите способ получения заказа.
        /// </summary>
        internal static string ChooseDeliveryType {
            get {
                return ResourceManager.GetString("ChooseDeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий адрес:
        ///
        ///{0}.
        /// </summary>
        internal static string CurrentAddress {
            get {
                return ResourceManager.GetString("CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        internal static string DeliveryTypeDelivery {
            get {
                return ResourceManager.GetString("DeliveryTypeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самовывоз.
        /// </summary>
        internal static string DeliveryTypePickUp {
            get {
                return ResourceManager.GetString("DeliveryTypePickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер строения.
        /// </summary>
        internal static string EnterBuilding {
            get {
                return ResourceManager.GetString("EnterBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите город.
        /// </summary>
        internal static string EnterCity {
            get {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите комментарий к адресу.
        /// </summary>
        internal static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер квартиры.
        /// </summary>
        internal static string EnterFlat {
            get {
                return ResourceManager.GetString("EnterFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер дома.
        /// </summary>
        internal static string EnterHouseNumber {
            get {
                return ResourceManager.GetString("EnterHouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставьте номер телефона с помощью кнопки меню или введите номер вручную.
        /// </summary>
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправлено СМС на номер {0}. Переотправка доступна через {1} секунд.
        /// </summary>
        internal static string EnterSms {
            get {
                return ResourceManager.GetString("EnterSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите улицу.
        /// </summary>
        internal static string EnterStreet {
            get {
                return ResourceManager.GetString("EnterStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не должно превышать {0} символов.
        /// </summary>
        internal static string ErrorLengthMax {
            get {
                return ResourceManager.GetString("ErrorLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите верное значение: {0}.
        /// </summary>
        internal static string InvalidAddressAttribute {
            get {
                return ResourceManager.GetString("InvalidAddressAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить адрес.
        /// </summary>
        internal static string NewAddress {
            get {
                return ResourceManager.GetString("NewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш заказ № {0} принят в работу. Ожидайте подтверждения.
        /// </summary>
        internal static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы поддерживаем только российские номера телефонов (начинаются с +7).
        /// </summary>
        internal static string OnlyRussianNumber {
            get {
                return ResourceManager.GetString("OnlyRussianNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес доставки:
        ///{0}
        ///
        ///Номер телефона:
        ///{1}.
        /// </summary>
        internal static string OrderSettings {
            get {
                return ResourceManager.GetString("OrderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон подтвержден!.
        /// </summary>
        internal static string PhoneConfirmed {
            get {
                return ResourceManager.GetString("PhoneConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить СМС.
        /// </summary>
        internal static string ResendSms {
            get {
                return ResourceManager.GetString("ResendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступна переотправка СМС.
        /// </summary>
        internal static string ResendSmsAvaliable {
            get {
                return ResourceManager.GetString("ResendSmsAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться номером телефона.
        /// </summary>
        internal static string SharePhone {
            get {
                return ResourceManager.GetString("SharePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропустить.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отправьте корректный {0}-значный код.
        /// </summary>
        internal static string SmsLengthError {
            get {
                return ResourceManager.GetString("SmsLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный код. Попробуйте еще раз или дождитесь переотправки.
        /// </summary>
        internal static string SmsWrong {
            get {
                return ResourceManager.GetString("SmsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказать!.
        /// </summary>
        internal static string TakeOrder {
            get {
                return ResourceManager.GetString("TakeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось распознать телефон. Попробуйте ввести в другом формате.
        /// </summary>
        internal static string WrongPhone {
            get {
                return ResourceManager.GetString("WrongPhone", resourceCulture);
            }
        }
    }
}
