//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTgBot.Infrastructure.Conversations.BotOwner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotOwnerText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotOwnerText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminTgBot.Infrastructure.Conversations.BotOwner.BotOwnerText", typeof(BotOwnerText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить супер админа.
        /// </summary>
        internal static string AddSuperAdmin {
            get {
                return ResourceManager.GetString("AddSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при добавлении супер админа. Попробуйте снова.
        /// </summary>
        internal static string AddSuperAdminError {
            get {
                return ResourceManager.GetString("AddSuperAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супер админ успешно добавлен.
        /// </summary>
        internal static string AddSuperAdminSuccess {
            get {
                return ResourceManager.GetString("AddSuperAdminSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к выбору действий.
        /// </summary>
        internal static string BackToMenuActions {
            get {
                return ResourceManager.GetString("BackToMenuActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите супер админа для сброса пароля.
        /// </summary>
        internal static string ChooseSuperAdminForResetPassowrd {
            get {
                return ResourceManager.GetString("ChooseSuperAdminForResetPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить создание супер админа?
        ///
        ///Логин: {0}
        ///Имя: {1}.
        /// </summary>
        internal static string ConfirmAddSuperAdmin {
            get {
                return ResourceManager.GetString("ConfirmAddSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нового супер админа
        ///Введите логин.
        /// </summary>
        internal static string EnterLogin {
            get {
                return ResourceManager.GetString("EnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя админа.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админ с таким логином уже существует.
        /// </summary>
        internal static string LoginAlreadyExists {
            get {
                return ResourceManager.GetString("LoginAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш новый пароль: &apos;{0}&apos;
        ///Пожалуйста, измените его в личном кабинете.
        /// </summary>
        internal static string NewPasswordReset {
            get {
                return ResourceManager.GetString("NewPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить пароль супер админу.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите действие.
        /// </summary>
        internal static string SelectMenu {
            get {
                return ResourceManager.GetString("SelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супер админ с id=&apos;{0}&apos; не найден.
        /// </summary>
        internal static string SuperAdminNotFound {
            get {
                return ResourceManager.GetString("SuperAdminNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найдено ни одного супер админа.
        /// </summary>
        internal static string SuperAdminsNotFound {
            get {
                return ResourceManager.GetString("SuperAdminsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в административную панель!
        ///
        ///Вы попали в раздел владельца телеграм бота. Этот раздел предназначен для создания Супер админов со всеми правами.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
